### ISSUE TITLE
Лишний пробел в документации

### ISSUE THREAD

**Issue by shalimski** [grumagargler/tester#11]
В разделе "Механизм заданий" пункт 3 есть лишний пробел.

> ... изменения на работу  программы.

**Comment by shalimski** [comment]
> В разделе "Механизм заданий" пункт 3 есть лишний пробел.
> 
> > ... изменения на работу  программы.

А гитхаб его сам убирает))

**Comment by grumagargler** [comment]
Спасибо! Поправлю

**Comment by grumagargler** [comment]
Всё, поправил, спасибо за въедливое чтение! :-)
