### ISSUE TITLE
Опечатка в документации

### ISSUE THREAD

**Issue by shalimski** [grumagargler/tester#12]
> фундаметального

**Comment by grumagargler** [comment]
Александр, а подскажите в каком разделе? по слову "фундаметального" не нашел поиск (www.test1c.com)

**Comment by shalimski** [comment]
![image](https://user-images.githubusercontent.com/1501405/55232750-6a493a00-5261-11e9-9461-d1f19016c55c.png)

В самом первом разделе

**Comment by grumagargler** [comment]
Спасибо! Поправил.
