### ISSUE TITLE
Ошибка в проверке шаблона?

### ISSUE THREAD

**Issue by MikolaKar** [grumagargler/tester#13]
При проверке шаблона, если в ячейке указан формат {* Текст}, то команда ПроверитьШаблон ( "" ); выдает ошибку: Недопустимое значение параметра (параметр номер '2'). 
Стоит поменять формат ячейки на {Звездочка}, или {ТекстЗвездочка}, или даже {Текст*Текст} - ошибок нет. Звездочка = *. Как-то в тексте отражается неверно - форматирует, вместо того, что бы отражаться...

**Comment by grumagargler** [comment]
Исправление вошло в 1.3.3.1
