### ISSUE TITLE
При попытке просмотра хронографа ошибка

### ISSUE THREAD

**Issue by BorisovVA** [grumagargler/tester#14]
При попытке просмотра сессия записи хронографа ошибка

{InformationRegister.Timelapse.Command.Open.CommandModule(37)}: Значение не является значением объектного типа (Scenario)
	p.Insert ( "Scenario", Value.Scenario );

1С:Предприятие 8.3 (8.3.13.1809)

**Comment by grumagargler** [comment]
День добрый!
Спасибо за сообщение!
Проверьте пожалуйста на версии 1.3.3.9, ошибка должна быть исправлена.

**Comment by BorisovVA** [comment]
Ошибка устранена, спасибо!
