### ISSUE TITLE
При открытии конфигурации ошибка setCaption

### ISSUE THREAD

**Issue by Bespalov-AV** [grumagargler/tester#15]
![Screenshot_51](https://user-images.githubusercontent.com/36464371/63753438-486de500-c8dd-11e9-85dc-cc8de9569d6f.png)
Ошибка при открытии. Если запускать из конфигуратора ошибки нет.
Версия 1.3.3.8
Проявляется на разных платформах.

**Comment by grumagargler** [comment]
День добрый!
Спасибо за сообщение!
Проверьте пожалуйста на версии 1.3.3.9, ошибка должна быть исправлена.

**Comment by Bespalov-AV** [comment]
Обновил. Ошибка осталась.
Попробовал создать пустую базу из CF ещё ошибки добавились

> CommonModule.DS.Module(256,10) Процедура Get уже определена.

Платформа 8.3.14.1854.
Может какие-то условия запуска нужны специальные?

**Comment by grumagargler** [comment]
Убедитесь пожалуйста, что вы запускаете тестер в тонком клиенте.

**Comment by Bespalov-AV** [comment]
Да действительно. Проблема была в толстом клиенте.
