### ISSUE TITLE
Падает в бесконечный цикл при попытке запустить студио код

### ISSUE THREAD

**Issue by Ndochp** [grumagargler/tester#16]
Проблема:
При запуске студии из формы сценария 1С падает в бесконечный цикл

Чувствую, что беда в  модуле команды запуска студии в repoData , но как чисто подправить слету не скажу. 

`&AtServer
Function repoData ( val Scenario, val Separator )
	
	table = getFolders ();
	application = DF.Pick ( Scenario, "Application" );
	row = table.Find ( application, "Application" );
	folder = row.Folder;
	vscode = row.VSCode;
	table.Delete ( row );
	looking = ( table.Count () > 0 );
	while ( looking ) do
		parent = FileSystem.GetParent ( folder, Separator );
		if ( parent = undefined ) then
			break;
		endif;
		for each row in table do
			if ( StrStartWith ( row.Folder, parent ) ) then
				folder = parent;
				looking = false;
				break;
			endif;
		enddo;
	enddo;
	return new Structure ( "Folder, VSCode", folder, vscode );
	
EndFunction
`

крутится в цикле, так как условие  ( StrStartWith ( row.Folder, parent ) ) не выполняется, в итоге на следующем шаге цикла не меняются ни фолдер, ни table ни parent. 

Воспроизведение: 
Сценарий:
Scenario	Документооборот.СогласованиеДоговораСПоставщиком.Сценарий1	
Scenario.Application	Документооборот 2018	

таблица каталогов
VSCode | Application | Folder
"" |   | "C:\Users\d.neumoychev\Dropbox\04 ИНФО\ТестерОбщиеТесты"
"" | Документооборот 2018 | "C:\GIT_REPO\DOC2018\Tests"

**Comment by grumagargler** [comment]
Покажите пожалуйста список смонтированных приложений (Меню / См. также / Репозитории).
Спасибо!

**Comment by grumagargler** [comment]
Спасибо еще раз за подробное описание проблемы, проверьте пожалуйста на версии 1.3.4.2

**Comment by Ndochp** [comment]
Так работает. Спасибо.
