### ISSUE TITLE
Не исчезает * на закладке Шаблон после записи сценария 

### ISSUE THREAD

**Issue by MikolaKar** [grumagargler/tester#2]
При редактировании Шаблона появляется * в закладке. После записи - не исчезает.

**Comment by grumagargler** [comment]
Да, такое поведение по дизайну. Смотрите, сценарий и его шаблон - одно целое, отдельно сохранить шаблон от сценария нельзя, и эта звезда показывает не то, что шаблон не сохранен, а его наличие как таковое. Это нужно для того, чтобы при открытии сценария, можно было сразу понять, что в сценарии есть шаблон, не переключаясь на вкладку с шаблоном.
Если звезда конфузит, можно заменить её на другой символ.

**Comment by MikolaKar** [comment]
Понятно. Я обратил внимание, потому как захотел удалить шаблон. Если удалить все строки в Шаблоне или очистить его- звезда остается, хотя шаблона нет. Тут вопрос, считать пустой шаблон шаблоном или нет...

**Comment by MikolaKar** [comment]
Остались колонки с форматами.
