### ISSUE TITLE
РежимРедактирования - Непосредственно

### ISSUE THREAD

**Issue by TeamBIOS** [grumagargler/tester#4]
Если у поля таблицы формы установлено свойство "РежимРедактирования" в значение "Непосредственно", то при записи теста появляется строка "Таблица.ИзменитьСтроку ();", которая при прогоне теста вызывает ошибку "Метод не может быть вызван для данного объекта (Таблица)"

**Comment by grumagargler** [comment]
Формирование некорректного метода является следствием ошибочного включения данного шага в формируемый платформой xml-журнал действий пользователя, на основании которого работает механизм записи сценария. Это проблема не конкретно Тестера, но и любых решений, в которых используется воспроизведение действий пользователя (сценарное тестирование, ваннеса и другие). Я не рекомендую использовать запись действий при разработке реальных сценариев. Значительно быстрее использовать программный доступ к тестируемому приложению через обертки методов Тестера.

**Comment by TeamBIOS** [comment]
Мы правильно понимаем, что Вы предлагает запрограммировать ввод данных в таблицу, а не записывать запись этой последовательность действий?

**Comment by grumagargler** [comment]
Да. Главная мысль такая: запись сценария в подавляющем большинстве случаев не позволяет воспроизвести последовательность этих действий без ошибок, как бы это удивительно не звучало. Я предлагаю программировать сценарии, а не записывать их, по нескольким причинам:
- значительно короче получается весь код сценария, так как служебные действия спрятаны в обертках
- работать с исходным кодом существенно проще, чем корректировать сгенерированный
- Методы-обертки создавалось специально для упрощения написания сценариев, продумывался также их состав как таковой, чтобы не усложнять работу специалистам без глубоких навыков программирования
- Кодирование сценария дает существенно больше пространства для маневра по части глубины тестирования как такового. Часть кода можно выносить в отдельные процедуры или сценарии-методы.

Если у вас есть другие вопросы на обсуждение, приходите в чат по адресу https://gitter.im/tester1c/Lobby

**Comment by grumagargler** [comment]
Для сравнения, вот такой код для заполнения материала:
```
Здесь ( "Выдача в производство*" );
Нажать ( "!МатериалыДобавить" );
Ввести ( "Материал", "Блок питания БП 12/2" );
```
